config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'git_org_analyzers#open_source_repositories'
  get '/git_analysis' => 'git_org_analyzers#open_source_repositories'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/git_org_analyzers_controller.rb
class GitOrgAnalyzersController < ApplicationController


  def open_source_repositories
  	@repository_details = GitRepositoryAnalyzer.new.analyze_github_repo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/git_org_analyzers_helper.rb
module GitOrgAnalyzersHelper
end

app/views/git_org_analyzers/open_source_repositories.html.erb
<%=link_to 'Download CSV', git_analysis_path(format: 'csv')%>

<h3> Most common languages used in Organization  </h3>
<table border="1">
  <thead>
    <tr>
      <th>Language</th>
      <th> Count</th>
    </tr>
  </thead>
  <tbody>
    <% @repository_details[:most_languages].each do |language| %>
      <tr>
        <td> <%= language[0]%> </td>
        <td> <%= language[1] %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3> Least common languages used in Organization </h3>
<table border="1">
  <thead>
    <tr>
      <th>Language</th>
      <th> Count</th>
    </tr>
  </thead>
  
  <tbody>
    <% @repository_details[:least_languages].each do |language| %>
      <tr>
        <td> <%= language[0]%> </td>
        <td> <%= language[1] %> </td>
      </tr>
    <%end%>
  </tbody>
</table>

<hr/>

<table border=1>
  <thead>
    <tr>
      <th>Repostory Name</th>
      <th>Language</th>
      <th>Created At</th>
    </tr>
  </thead>

  <tbody>
    <% @repository_details[:repositories].each do |repository|%>
      <tr>
        <td><%= repository[:repository_name] %></td>
        <td><%= repository[:repository_languages] %></td>
        <td><%= repository[:created_at] %></td>
      </tr>
    <%end%>
  </tbody>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitAnalyzer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>